apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zipk0p0br-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zipk0p0br-python 
  name: zipk0p0br-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zipk0p0br-python 
